### ISSUE TITLE
適切なリポジトリへのライセンスが設定されていない。

### ISSUE THREAD

**Issue by waxsd100** [Ai-Akaishi/LongestRoad#1]
@Ai-Akaishi
コードのLICENCE ファイルが存在しないため、No Licence状態(GitHub上以外での複製、改変の不許可)となっている。

![image](https://user-images.githubusercontent.com/12383342/108558260-02140d80-733d-11eb-88ce-f5d9824914d5.png)

ついでに、Readmeに対応Minecraft Ver記載があったら嬉しかったり。

 参考:

後からLICENCEを追加する方法
https://docs.github.com/ja/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by Ai-Akaishi** [comment]
MITライセンスに設定しました。
